### PR TITLE
Use the controller's JsonSerializerSettings.

### PR DESCRIPTION
**Pull request by einarwh**
The example in the Swagger docs should use the same JsonSerializerSettings as the controller, to ensure that the example is accurate.

That is, Swashbuckle.Examples should check to see if there are controller-specific serialization settings before using default settings.  

For reference:
https://blogs.msdn.microsoft.com/jmstall/2012/05/11/per-controller-configuration-in-webapi/

### CODE REVIEW

**Comment by ntregillus** [comment]
good addition!

**Comment by mattfrear** [comment]
Sorry for the delay - GitHub isn't sending me notifications and I don't know why.

Thanks for the fix!

**Comment by mattfrear** [comment]
Hmm this actually introduced a bug - if any of your Request or Response example properties were null, then Swagger was throwing an exception:
`TypeError: Swagger 2.0 does not support null types ([object Object])`

The fix is to set the `serializerSettings.NullValueHandling = NullValueHandling.Ignore` like I was already doing.

Fixed in commit cbc864d416d18e35104c00c6d780defbd393c6e2

**Comment by einarwh** [comment]
Ooops sorry about that, I should have tested more thoroughly. Thanks for including this.

**Pull request merged**
